name: flood_app_dev
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - cherrypy
  - click
  - flask
  - flask-cors
  - landlab==2.10
  - rasterio
  - tqdm
  - toml
  - matplotlib
  # testing
  - pytest
  - pytest-cov
  - pytest-datadir
  # linting
  - nox
  - pre-commit
  - ruff
  # docs
  - sphinx
  - furo
