[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flood_app"
description = """
A RESTful web service for watershed-scale simulation of surface runoff and
soil infiltration using Landlab model components.
"""
authors = [
  {name = "Tian Gan", email = "gantian127@gmail.com"},
  {name = "CSDMS"},
]
maintainers = [
  {name = "Tian Gan", email = "gantian127@gmail.com"},
]
keywords = [
  "landlab",
  "overland flow",
  "soil infiltration",
  "flood simulation",
  "hydrology",
  "earth science",
  "participatory modeling",
]
license = {file = "LICENSE.rst"}
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: Implementation :: CPython",
  "Topic :: Scientific/Engineering :: Hydrology",
  "Topic :: Scientific/Engineering :: Physics",
]
requires-python = ">=3.11"
dependencies = [
  "numpy",
  "cherrypy",
  "click",
  "flask",
  "flask-cors",
  "landlab==2.10.0",
  "rasterio",
  "tqdm",
  "toml",
]
dynamic = ["readme", "version"]

[project.urls]
Documentation = "https://flood-app.readthedocs.io"
Repository = "https://github.com/gantian127/flood_app"
Changelog = "https://github.com/gantian127/flood_app/blob/master/CHANGES.rst"

[project.optional-dependencies]
dev = [
  "nox",
  "pre-commit",
  "ruff",
]
testing = [
  "pytest",
  "pytest-cov",
  "pytest-datadir",
]

[project.scripts]
start-app = "flood_app.cli:main"

[tool.setuptools]
packages = ["flood_app"]

[tool.setuptools.package-data]
"flood_app" = ["templates/*", "static/*", "config_file.toml"]

[tool.setuptools.dynamic]
readme = {file = ["README.rst"]}
version = {attr = "flood_app._version.__version__"}

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["flood_app", "tests"]
norecursedirs = [".*", "*.egg*", "build", "dist", "examples"]
addopts = """
  --ignore setup.py
  --tb native
  --strict
  --durations 16
  --doctest-modules
  -vvv
"""
doctest_optionflags = [
  "NORMALIZE_WHITESPACE",
  "IGNORE_EXCEPTION_DETAIL",
  "ALLOW_UNICODE",
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
