[terrain]
grid_file = ""
nodata_value = -9999
outlet_id = -1

[output]
output_folder = ""
plot_olf = true
plot_inf = true

[model_run]
model_run_time = 200
storm_duration = 10
time_step = 2
activate_inf = false
time_out = 300

[infil_info]
conductivity_file = ""
hydraulic_conductivity = 1e-7
soil_water_file = ""
soil_water_infiltration_depth = 1e-5
soil_bulk_density = 1590.0
rock_density = 2650.0
initial_soil_moisture_content = 0.15
soil_type = "sandy loam"
volume_fraction_coarse_fragments = 0.2
coarse_sed_flag = false
surface_water_minimum_depth = 1e-8
soil_pore_size_distribution_index = false
soil_bubbling_pressure = false
wetting_front_capillary_pressure_head = false

[olf_info]
rain_file = ""
rain_intensity = 59.2
surface_water_file = ""
surface_water_depth = 1e-12
steep_slopes = true
alpha = 0.7
mannings_n = 0.03
g = 9.80665
theta = 0.8
