name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Build and install package
        run: |
          pip install -e .

      - name: Test
        working-directory: ${{ github.workspace }}/tests
        run: |
          python -c 'import flood_app' && pytest
